### ISSUE TITLE
Not clear where to find the labels of the data

### ISSUE THREAD

**Issue by lunoack** [jdpulgarin/Tennis-MoCap#1]
I'm working with the Tennis-MoCap dataset, and I'm having trouble finding the labels for the data. I've looked through the documentation and the dataset files, but I can't seem to locate them. Can someone please point me to the correct location or provide further instructions on how to find the labels?

**Comment by jdpulgarin** [comment]
I didn't realize there was a lack of labels, so I provided a .csv based on your observation and included other labels related to tennis strokes. Thanks a lot Luca.
